project_name: prompt-sync

builds:
  - id: prompt-sync
    main: ./cmd/prompt-sync
    binary: prompt-sync
    ldflags: -s -w
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - id: archive
    builds: [prompt-sync]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: kovyrin
    name: prompt-sync

# Optional: Homebrew tap definition (requires a writable tap repository)
# Commented out for now – uncomment when the tap is ready.
# brews:
#   - name: prompt-sync
#     tap:
#       owner: kovyrin
#       name: homebrew-tap
#     homepage: "https://github.com/kovyrin/prompt-sync"
#     description: "Prompt manager for AI prompts & rules"
#     test: "prompt-sync --help"
